# fly.toml app configuration file generated for games-html-api on 2023-08-21T11:08:42-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "games-html-api"
primary_region = "qro"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
